### ISSUE TITLE
Splash screen appears but then closes and nothing happens

### ISSUE THREAD

**Issue by tivrfoa** [chrisseaton/c1visualizer#1]
Hi,

I got the latest release.

When I run `c1visualizer-1.7/c1visualizer/bin $ ./c1visualizer`, the splash screen appears, then it closes and nothings happens. :(

```shell
$ ./c1visualizer
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/lesco/Downloads/c1visualizer-1.7/c1visualizer/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
$
```

What am I doing wrong, please?

**uname -a**
```shell
Linux lesco-Lenovo-IdeaPad-S145-15API 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**java --version**
```shell
openjdk 11.0.12-testing 2021-07-20
OpenJDK Runtime Environment (slowdebug build 11.0.12-testing+0-builds.shipilev.net-openjdk-jdk11-b292-20210601)
OpenJDK 64-Bit Server VM (slowdebug build 11.0.12-testing+0-builds.shipilev.net-openjdk-jdk11-b292-20210601, mixed mode)
```

**Comment by tivrfoa** [comment]
I exported *jdkhome*, but same result ... :/

```
$ export jdkhome=$JAVA_HOME
$ echo $jdkhome
/home/lesco/dev/Java/openjdk-jdk11-linux-x86_64-server-slowdebug/jdk
```

**Comment by chrisseaton** [comment]
It's probably sensitive on the Java version, for some reason - it's fairly old, unmaintained software.

I used `sdkman` to install a contemporary Java - `8.292.10.1-amzn` - and it works fine with that.

```
% JAVA_HOME=~/.sdkman/candidates/java/8.292.10.1-amzn jdkhome=$JAVA_HOME PATH=$JAVA_HOME/bin:$PATH c1visualizer/bin/c1visualizer 
```

What are you trying to achieve? Just disassembly? Another option for that is Seafoam's `cfg2asm` command - https://github.com/Shopify/seafoam#disassembling.

**Comment by chrisseaton** [comment]
It should work with Java 11 with `-J--illegal-access=warn`... but it doesn't. Not sure why. Stick with 8.

**Comment by tivrfoa** [comment]
Thank you Chris!
It worked with java 8:
```
$ java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
```
>it's fairly old, unmaintained software

Yes. It looks old. :]

>What are you trying to achieve? Just disassembly?

My goal was just to look at the assembly generated by JIT compiler.

>Another option for that is Seafoam's cfg2asm command

I'll take a look. Thank you very much!
